import { St2 } from "./St2";
import { Starm } from "./Starm";
import { Stb } from "./Stb";
import { Stcp } from "./Stcp";
import { StCt } from "./StCt";
import { StFnc } from "./StFnc";
import { Stl } from "./Stl";
import { Stmaq } from "./Stmaq";
import { Stpe } from "./Stpe";
import { StPrecos } from "./StPrecos";
import { StQuant } from "./StQuant";
import { StVtdoc } from "./StVdoc";
import { StVtman } from "./StVtman";
import { StVtTrailer } from "./StVtTrailer";

export interface St {
    ststamp: string;
    referenc: string;
    obs: string;
    refornec: string;
    tipo: string;
    codigoBarras: string;
    status: string;
    unidade: string;
    descricao: string;
    servico: boolean;
    tabiva: number;
    txiva: number;
    valor: number;
    ivainc: boolean;
    codfam: string;
    familia: string;
    codsubfam: string;
    subfamilia: string;
    codarm: string;
    armazem: string;
    codmarca: number;
    marca: string;
    matricula: string;
    modelo: string;
    motor: string;
    chassis: string;
    anofab: number;
    tara: number;
    pesobruto: number;
    combustivel: boolean;
    tipoCombustivel: string;
    codfab: number;
    fabricante: string;
    negativo: boolean;
    viatura: boolean;
    avisanegativo: boolean;
    descontinuado: boolean;
    ligaprojecto: boolean;
    composto: boolean;
    stock: number;
    ultimopreco: number;
    precoponderado: number;
    imagem: string;
    codigobarra: string;
    codigoQr: string;
    codtrailer: number;
    trailer: boolean;
    usaconvunid: boolean;
    quantidade: number;
    unidsaida: string;
    usadoprod: boolean;
    dimensao: boolean;
    devolc: boolean;
    usaserie: boolean;
    stockmin: number;
    stockmax: number;
    reserva: number;
    encomenda: number;
    nmovstk: boolean;
    pos: boolean;
    motorista: string;
    departanto: string;
    ccusto: string;
    cilindrada: number;
    companhia: string;
    contrato: string;
    inicio: string;
    termino: string;
    valorLeasing: number;
    mensalidade: number;
    bloqueado: boolean;
    assentos: number;
    portas: number;
    data: string;
    trailref: string;
    traildesc: string;
    anomodelo: number;
    eixos: number;
    pneus: number;
    carga: number;
    vendido: number;
    comprado: number;
    obterpeso: boolean;
    peso: number;
    volume: number;
    usalote: boolean;
    ivametade: boolean;
    cpoc: string;
    contaInv: string;
    contaCev: string;
    contaReo: string;
    contaCoi: string;
    nofrota: string;
    cor: string;
    gasoleo: boolean;
    naovisisvel: boolean;
    activo: boolean;
    tipoartigo: number;
    quantvenda: number;
    usaquant2: boolean;
    st2: St2;
    stPrecos: StPrecos[];
    stcp: Stcp[];
    stFnc: StFnc[];
    starm: Starm[];
    stVtman: StVtman[];
    stVtdoc: StVtdoc[];
    stVtTrailer: StVtTrailer[];
    stCt: StCt[];
    stQuant: StQuant[];
    disciplina: boolean;
    sigla: string;
    credac: number;
    cargahtotal: number;
    cargahteorica: number;
    cargahpratica: number;
    prec: boolean;
    stl: Stl[];
    stb: Stb[];
    stpe: Stpe[];
    stmaq: Stmaq[];
    multa: boolean;
    bilhete: boolean;
    bilheteespecial: boolean;
    tipoProduto: number;
}