import { St } from "./St";
import { StDrp } from "./StDrp";
import { StDrpc } from "./StDrpc";
import { Stimpar } from "./Stimpar";
import { Streaval } from "./Streaval";
import { Streval } from "./Streval";

export interface St2 {
    ststamp: string;
    data: string;
    datain: string;
    depin: string;
    localizacao: string;
    nrelement: number;
    nranos: number;
    vidafis: number;
    anomvalia: number;
    reinsvest: boolean;
    ndep: boolean;
    quotas: boolean;
    duodessimos: boolean;
    usado: boolean;
    repactivo: boolean;
    activorep: string;
    valmvaliacusto: number;
    valmvaliareivest: number;
    valAquis: number;
    valAquisact: number;
    quantdep: number;
    quantrec: number;
    perdas: number;
    valResidual: number;
    valFiscal: number;
    codAmotr: number;
    amotr: string;
    naturAct: string;
    codtipoact: string;
    tipoact: string;
    tipoartigo: number;
    valMatricial: number;
    deptotalnact: number;
    deptotalact: number;
    valdepact: number;
    valquantesc: number;
    percdep: number;
    percndep: number;
    perctaxaceite: number;
    quotasperdidas: number;
    deptotaisperdidas: number;
    sNC: string;
    depex: string;
    depacu: string;
    mvalia: string;
    venda: string;
    aliena: string;
    abate: string;
    reaval: string;
    perdaimpa: string;
    reversimpa: string;
    perdaimpacum: string;
    excedreval: string;
    passimposto: string;
    menosvalia: string;
    vdreal: number;
    valavaliac: number;
    datavaliac: string;
    duracao: number;
    datafim: string;
    databate: string;
    valvenda: number;
    motivo: string;
    grupo: string;
    subgrupo: string;
    origem: string;
    oristamp: string;
    cambio: number;
    moeda: string;
    percent: number;
    st: St;
    drp: StDrp[];
    stDrpc: StDrpc[];
    stimpar: Stimpar[];
    streaval: Streaval[];
    streval: Streval[];
}