import { formasp } from "src/app/frm-rcl/TodosRCL";
import { Fcc } from "../Facc/Fcc";
import { Pgfl } from "./Pgfl";

export interface Pgf {
    pgfstamp: string;
    numero: number;
    data: string;
    no: string;
    nome: string;
    moeda: string;
    nuit: number;
    morada: string;
    localidade: string;
    banco: string;
    total: number;
    mtotal: number;
    obs: string;
    process: boolean;
    dprocess: string;
    anulado: boolean;
    ccusto: string;
    nrFornec: string;
    numdoc: number;
    sigla: string;
    tpgfstamp: string;
    nomedoc: string;
    codmovcc: number;
    descmovcc: string;
    integra: boolean;
    nodiario: number;
    diario: string;
    ndocCont: number;
    descDocCont: string;
    cambiousd: number;
    moeda2: string;
    pjno: number;
    pjstamp: string;
    pjNome: string;
    fncstamp: string;
    descontofin: number;
    mDescontofin: number;
    perdescfin: number;
    rcladiant: boolean;
    usrstamp: string;
    ccustamp: string;
    refornec: string;
    fcc: Fcc[];
    formasp: formasp[];
    pgfl: Pgfl[];
    codmovtz: number;
    descmovtz: string;
}