

export interface AspnetUser{
  id	:string;
 usrstamp	:string;	
 numero	:number
 tipoAcesso	:number
 nome	:string;	
  login	:string;	
 pos	:boolean;
 usradmin	:boolean;
codccu	:string;	
ccusto	:string;	
contacto	:string;	
codposto	:number
 posto	:string;	
 pw	:string;	
 mostralimpar	:boolean;
codtz	:number
contaTesoura	:string;	
codarm	:number
 armazem	:string;	
  supervisor	:boolean;
 mudasenha	:boolean;
  sigla	:string;	
codgrupo	:number
  grupo	:string;	
  aprovaPagamento	:boolean;
 desconto	:boolean;
 fechacaixa	:boolean;
  abrecaixa	:boolean;
  status	:string;	
codstatus	:string;	
contasstamp	:string;	
 valorMaxPagamento	:number
 mostraprcompra	:boolean;
  reabrePj	:boolean;
  alteracambio	:boolean;
  alteraNumero	:boolean;
 mostrasaldo	:boolean;
 mostraextrato	:boolean;
 naoMostrafacturacao	:boolean;
 naoMostraProcessos	:boolean;
 naoMostraCadastro	:boolean;
 naoMostraConfig	:boolean;
 naoMostracompras	:boolean;
 naoMostravendas	:boolean;
 naoMostraAnalises	:boolean;
 usanormal	:boolean;
  impnormal	:string;	
  imppos	:string;	
  lingua	:number
  armazemstamp	:string;	
ccustamp	:string;	
 tipousr	:number
 naoaltera	:boolean;
clstamp	:string;
 pestam	:string;
 fncstam	:string;
 userName	:string;
 normalizedUserName	:string;
  email	:string;
 normalizedemail	:string;
  emailConfirmed	:boolean;
 passwordHash	:string;	
  securitystamp	:string;	
concurrencystamp	:string;	
 phoneNumber	:string;	
 phoneNumberConfirmed	:boolean;
 twoFactorenabled	:boolean;
  lockoutend	:Date;	
  lockoutenabled	:boolean;
  accessFailedCont	:number
 tipoPerfil	:number;
    
	
}